server:
  port: 8888
spring:
  application:
    name: gateway
    cloud:
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8760/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'