server:
  port: 8888

spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: gateway


management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  register-with-eureka: true
  fetch-registry: true
  service-url:
    defaultZone: http://localhost:8710/eureka
